;
STARTUP
         DEFM @@HELLO@THERE@AND@WELCOME
         DEFM @TO@MINE@[@A@PROGRAM@WRIT
         DEFM TE
         DEFM N@BY@JASON@BROOKS^@@@THE@O
         DEFM BJECT@OF@THE@GAME@IS@TO@CL
         DEFM EAR@THE@GRID@OF@ALL@MINES
         DEFM [@YOU@CAN@DO@THIS@BY@PLACI
         DEFM NG@THE@POINTER@ON@THE@GRI
         DEFM D
         DEFM @SQUARE@AND@PRESSING@FIRE
         DEFM ^@@IF@YOU@UNCOVER@A@BLANK
         DEFM @
         DEFM SQUARE@[@YOU@WILL@BE@ABLE
         DEFM @T
         DEFM O@CLEAR@ALL@BLANKS@BY@CLIC
         DEFM KING@THE@FIRE@BUTTON@TWICE
         DEFM ^@@IF@YOU@ACCIDENTALLY@UNC
         DEFM OVER@A@MINE@TH
         DEFM E@GRID@WILL@BLOW@UP^@@I
         DEFM F@YOU@KNOW@THE@WHERE@ABOU
         DEFM T
         DEFM S@OF@A@MINE@THEN@SIMPLY@PL
         DEFM ACE@A@FLAG@OVER@THE@SPOT^
         DEFM @^@@@@
         DEFM @AFTER@ALL@OF@THIS@I@WOUL
         DEFM D@LIKE@TO@ACKNOWLEDGE@MY@T
         DEFM HANKS@TO@ALL@WHO@KNOW@ME@I
         DEFM NCLUDING[@JUSTIN@CHADWICK[
         DEFM @DAN@WATT[@JOHN@AND@ROY@AN
         DEFM D@ESPECIALLY@MANDY@HAVE@F
         DEFM UN[@LOADSALUV@JASE@^^^^^@@
         DEFB 0
*f,varibles.adm
